CREATE OR REPLACE STREAM "MEAN_SENTIMENT" 
(score  DOUBLE);

CREATE OR REPLACE PUMP "STREAM_PUMP" AS 
INSERT INTO "MEAN_SENTIMENT"
SELECT STREAM AVG("score") OVER lastquarter
FROM "SOURCE_SQL_STREAM_001"
WINDOW
lastquarter AS (RANGE INTERVAL '1' MINUTE PRECEDING);